/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YouthRouteImport } from './routes/youth'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SafeguardingPolicyRouteImport } from './routes/safeguarding-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestSupportRouteImport } from './routes/request-support'
import { Route as RegisterProviderRouteImport } from './routes/register-provider'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FindHelpRouteImport } from './routes/find-help'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApprenticeshipsRouteImport } from './routes/apprenticeships'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YouthIndexRouteImport } from './routes/youth.index'
import { Route as RequestMentorshipIndexRouteImport } from './routes/request-mentorship.index'
import { Route as ApprenticeshipsIndexRouteImport } from './routes/apprenticeships.index'
import { Route as YouthRegisterRouteImport } from './routes/youth.register'
import { Route as YouthPostOpportunityRouteImport } from './routes/youth.post-opportunity'
import { Route as YouthOpportunitiesRouteImport } from './routes/youth.opportunities'
import { Route as RequestTokenRouteImport } from './routes/request.$token'
import { Route as RequestMentorshipMentorIdRouteImport } from './routes/request-mentorship.$mentorId'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as MyListingTokenRouteImport } from './routes/my-listing.$token'
import { Route as MentorsInterestRouteImport } from './routes/mentors.interest'
import { Route as FeedbackTokenRouteImport } from './routes/feedback.$token'
import { Route as ApprenticeshipsRegisterProviderRouteImport } from './routes/apprenticeships.register-provider'
import { Route as ApprenticeshipsRegisterApprenticeRouteImport } from './routes/apprenticeships.register-apprentice'
import { Route as ApprenticeshipsOpportunitiesRouteImport } from './routes/apprenticeships.opportunities'
import { Route as ApprenticeshipsMentorsRouteImport } from './routes/apprenticeships.mentors'
import { Route as ApprenticeshipsImpactRouteImport } from './routes/apprenticeships.impact'
import { Route as ApprenticeshipsBecomeMentorRouteImport } from './routes/apprenticeships.become-mentor'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMyRequestsRouteImport } from './routes/_authenticated/my-requests'
import { Route as AuthenticatedMyAdvertRouteImport } from './routes/_authenticated/my-advert'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as YouthParentConsentTokenRouteImport } from './routes/youth.parent-consent.$token'
import { Route as DirectoryTypeIdRouteImport } from './routes/directory.$type.$id'
import { Route as ApiPublicContactRequestRouteImport } from './routes/api/public/contact-request'
import { Route as AuthenticatedYouthPortfolioRouteImport } from './routes/_authenticated/youth.portfolio'
import { Route as AuthenticatedAdminYouthOpportunitiesRouteImport } from './routes/_authenticated/admin/youth-opportunities'
import { Route as AuthenticatedAdminNoticeboardRouteImport } from './routes/_authenticated/admin/noticeboard'
import { Route as AuthenticatedAdminApprenticeshipsRouteImport } from './routes/_authenticated/admin/apprenticeships'
import { Route as AuthenticatedAdminYouthIndexRouteImport } from './routes/_authenticated/admin/youth.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AuthenticatedAdminYouthIdRouteImport } from './routes/_authenticated/admin/youth.$id'
import { Route as AuthenticatedAdminProvidersIdRouteImport } from './routes/_authenticated/admin/providers/$id'
import { Route as AuthenticatedAdminApprenticesIdRouteImport } from './routes/_authenticated/admin/apprentices.$id'

const YouthRoute = YouthRouteImport.update({
  id: '/youth',
  path: '/youth',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeguardingPolicyRoute = SafeguardingPolicyRouteImport.update({
  id: '/safeguarding-policy',
  path: '/safeguarding-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestSupportRoute = RequestSupportRouteImport.update({
  id: '/request-support',
  path: '/request-support',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterProviderRoute = RegisterProviderRouteImport.update({
  id: '/register-provider',
  path: '/register-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FindHelpRoute = FindHelpRouteImport.update({
  id: '/find-help',
  path: '/find-help',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprenticeshipsRoute = ApprenticeshipsRouteImport.update({
  id: '/apprenticeships',
  path: '/apprenticeships',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YouthIndexRoute = YouthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => YouthRoute,
} as any)
const RequestMentorshipIndexRoute = RequestMentorshipIndexRouteImport.update({
  id: '/request-mentorship/',
  path: '/request-mentorship/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprenticeshipsIndexRoute = ApprenticeshipsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApprenticeshipsRoute,
} as any)
const YouthRegisterRoute = YouthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => YouthRoute,
} as any)
const YouthPostOpportunityRoute = YouthPostOpportunityRouteImport.update({
  id: '/post-opportunity',
  path: '/post-opportunity',
  getParentRoute: () => YouthRoute,
} as any)
const YouthOpportunitiesRoute = YouthOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => YouthRoute,
} as any)
const RequestTokenRoute = RequestTokenRouteImport.update({
  id: '/request/$token',
  path: '/request/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestMentorshipMentorIdRoute =
  RequestMentorshipMentorIdRouteImport.update({
    id: '/request-mentorship/$mentorId',
    path: '/request-mentorship/$mentorId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingTokenRoute = MyListingTokenRouteImport.update({
  id: '/my-listing/$token',
  path: '/my-listing/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsInterestRoute = MentorsInterestRouteImport.update({
  id: '/mentors/interest',
  path: '/mentors/interest',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackTokenRoute = FeedbackTokenRouteImport.update({
  id: '/feedback/$token',
  path: '/feedback/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprenticeshipsRegisterProviderRoute =
  ApprenticeshipsRegisterProviderRouteImport.update({
    id: '/register-provider',
    path: '/register-provider',
    getParentRoute: () => ApprenticeshipsRoute,
  } as any)
const ApprenticeshipsRegisterApprenticeRoute =
  ApprenticeshipsRegisterApprenticeRouteImport.update({
    id: '/register-apprentice',
    path: '/register-apprentice',
    getParentRoute: () => ApprenticeshipsRoute,
  } as any)
const ApprenticeshipsOpportunitiesRoute =
  ApprenticeshipsOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => ApprenticeshipsRoute,
  } as any)
const ApprenticeshipsMentorsRoute = ApprenticeshipsMentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => ApprenticeshipsRoute,
} as any)
const ApprenticeshipsImpactRoute = ApprenticeshipsImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => ApprenticeshipsRoute,
} as any)
const ApprenticeshipsBecomeMentorRoute =
  ApprenticeshipsBecomeMentorRouteImport.update({
    id: '/become-mentor',
    path: '/become-mentor',
    getParentRoute: () => ApprenticeshipsRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyRequestsRoute = AuthenticatedMyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyAdvertRoute = AuthenticatedMyAdvertRouteImport.update({
  id: '/my-advert',
  path: '/my-advert',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const YouthParentConsentTokenRoute = YouthParentConsentTokenRouteImport.update({
  id: '/parent-consent/$token',
  path: '/parent-consent/$token',
  getParentRoute: () => YouthRoute,
} as any)
const DirectoryTypeIdRoute = DirectoryTypeIdRouteImport.update({
  id: '/$type/$id',
  path: '/$type/$id',
  getParentRoute: () => DirectoryRoute,
} as any)
const ApiPublicContactRequestRoute = ApiPublicContactRequestRouteImport.update({
  id: '/api/public/contact-request',
  path: '/api/public/contact-request',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedYouthPortfolioRoute =
  AuthenticatedYouthPortfolioRouteImport.update({
    id: '/youth/portfolio',
    path: '/youth/portfolio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminYouthOpportunitiesRoute =
  AuthenticatedAdminYouthOpportunitiesRouteImport.update({
    id: '/admin/youth-opportunities',
    path: '/admin/youth-opportunities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNoticeboardRoute =
  AuthenticatedAdminNoticeboardRouteImport.update({
    id: '/admin/noticeboard',
    path: '/admin/noticeboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminApprenticeshipsRoute =
  AuthenticatedAdminApprenticeshipsRouteImport.update({
    id: '/admin/apprenticeships',
    path: '/admin/apprenticeships',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminYouthIndexRoute =
  AuthenticatedAdminYouthIndexRouteImport.update({
    id: '/admin/youth/',
    path: '/admin/youth/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminYouthIdRoute =
  AuthenticatedAdminYouthIdRouteImport.update({
    id: '/admin/youth/$id',
    path: '/admin/youth/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProvidersIdRoute =
  AuthenticatedAdminProvidersIdRouteImport.update({
    id: '/admin/providers/$id',
    path: '/admin/providers/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminApprenticesIdRoute =
  AuthenticatedAdminApprenticesIdRouteImport.update({
    id: '/admin/apprentices/$id',
    path: '/admin/apprentices/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/apprenticeships': typeof ApprenticeshipsRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/donate': typeof DonateRoute
  '/find-help': typeof FindHelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/register-provider': typeof RegisterProviderRoute
  '/request-support': typeof RequestSupportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safeguarding-policy': typeof SafeguardingPolicyRoute
  '/terms': typeof TermsRoute
  '/youth': typeof YouthRouteWithChildren
  '/my-advert': typeof AuthenticatedMyAdvertRoute
  '/my-requests': typeof AuthenticatedMyRequestsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/apprenticeships/become-mentor': typeof ApprenticeshipsBecomeMentorRoute
  '/apprenticeships/impact': typeof ApprenticeshipsImpactRoute
  '/apprenticeships/mentors': typeof ApprenticeshipsMentorsRoute
  '/apprenticeships/opportunities': typeof ApprenticeshipsOpportunitiesRoute
  '/apprenticeships/register-apprentice': typeof ApprenticeshipsRegisterApprenticeRoute
  '/apprenticeships/register-provider': typeof ApprenticeshipsRegisterProviderRoute
  '/feedback/$token': typeof FeedbackTokenRoute
  '/mentors/interest': typeof MentorsInterestRoute
  '/my-listing/$token': typeof MyListingTokenRoute
  '/profile/$id': typeof ProfileIdRoute
  '/request-mentorship/$mentorId': typeof RequestMentorshipMentorIdRoute
  '/request/$token': typeof RequestTokenRoute
  '/youth/opportunities': typeof YouthOpportunitiesRoute
  '/youth/post-opportunity': typeof YouthPostOpportunityRoute
  '/youth/register': typeof YouthRegisterRoute
  '/apprenticeships/': typeof ApprenticeshipsIndexRoute
  '/request-mentorship/': typeof RequestMentorshipIndexRoute
  '/youth/': typeof YouthIndexRoute
  '/admin/apprenticeships': typeof AuthenticatedAdminApprenticeshipsRoute
  '/admin/noticeboard': typeof AuthenticatedAdminNoticeboardRoute
  '/admin/youth-opportunities': typeof AuthenticatedAdminYouthOpportunitiesRoute
  '/youth/portfolio': typeof AuthenticatedYouthPortfolioRoute
  '/api/public/contact-request': typeof ApiPublicContactRequestRoute
  '/directory/$type/$id': typeof DirectoryTypeIdRoute
  '/youth/parent-consent/$token': typeof YouthParentConsentTokenRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/apprentices/$id': typeof AuthenticatedAdminApprenticesIdRoute
  '/admin/providers/$id': typeof AuthenticatedAdminProvidersIdRoute
  '/admin/youth/$id': typeof AuthenticatedAdminYouthIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/youth/': typeof AuthenticatedAdminYouthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/donate': typeof DonateRoute
  '/find-help': typeof FindHelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/register-provider': typeof RegisterProviderRoute
  '/request-support': typeof RequestSupportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safeguarding-policy': typeof SafeguardingPolicyRoute
  '/terms': typeof TermsRoute
  '/my-advert': typeof AuthenticatedMyAdvertRoute
  '/my-requests': typeof AuthenticatedMyRequestsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/apprenticeships/become-mentor': typeof ApprenticeshipsBecomeMentorRoute
  '/apprenticeships/impact': typeof ApprenticeshipsImpactRoute
  '/apprenticeships/mentors': typeof ApprenticeshipsMentorsRoute
  '/apprenticeships/opportunities': typeof ApprenticeshipsOpportunitiesRoute
  '/apprenticeships/register-apprentice': typeof ApprenticeshipsRegisterApprenticeRoute
  '/apprenticeships/register-provider': typeof ApprenticeshipsRegisterProviderRoute
  '/feedback/$token': typeof FeedbackTokenRoute
  '/mentors/interest': typeof MentorsInterestRoute
  '/my-listing/$token': typeof MyListingTokenRoute
  '/profile/$id': typeof ProfileIdRoute
  '/request-mentorship/$mentorId': typeof RequestMentorshipMentorIdRoute
  '/request/$token': typeof RequestTokenRoute
  '/youth/opportunities': typeof YouthOpportunitiesRoute
  '/youth/post-opportunity': typeof YouthPostOpportunityRoute
  '/youth/register': typeof YouthRegisterRoute
  '/apprenticeships': typeof ApprenticeshipsIndexRoute
  '/request-mentorship': typeof RequestMentorshipIndexRoute
  '/youth': typeof YouthIndexRoute
  '/admin/apprenticeships': typeof AuthenticatedAdminApprenticeshipsRoute
  '/admin/noticeboard': typeof AuthenticatedAdminNoticeboardRoute
  '/admin/youth-opportunities': typeof AuthenticatedAdminYouthOpportunitiesRoute
  '/youth/portfolio': typeof AuthenticatedYouthPortfolioRoute
  '/api/public/contact-request': typeof ApiPublicContactRequestRoute
  '/directory/$type/$id': typeof DirectoryTypeIdRoute
  '/youth/parent-consent/$token': typeof YouthParentConsentTokenRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/apprentices/$id': typeof AuthenticatedAdminApprenticesIdRoute
  '/admin/providers/$id': typeof AuthenticatedAdminProvidersIdRoute
  '/admin/youth/$id': typeof AuthenticatedAdminYouthIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/youth': typeof AuthenticatedAdminYouthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/apprenticeships': typeof ApprenticeshipsRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/donate': typeof DonateRoute
  '/find-help': typeof FindHelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/register-provider': typeof RegisterProviderRoute
  '/request-support': typeof RequestSupportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safeguarding-policy': typeof SafeguardingPolicyRoute
  '/terms': typeof TermsRoute
  '/youth': typeof YouthRouteWithChildren
  '/_authenticated/my-advert': typeof AuthenticatedMyAdvertRoute
  '/_authenticated/my-requests': typeof AuthenticatedMyRequestsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/apprenticeships/become-mentor': typeof ApprenticeshipsBecomeMentorRoute
  '/apprenticeships/impact': typeof ApprenticeshipsImpactRoute
  '/apprenticeships/mentors': typeof ApprenticeshipsMentorsRoute
  '/apprenticeships/opportunities': typeof ApprenticeshipsOpportunitiesRoute
  '/apprenticeships/register-apprentice': typeof ApprenticeshipsRegisterApprenticeRoute
  '/apprenticeships/register-provider': typeof ApprenticeshipsRegisterProviderRoute
  '/feedback/$token': typeof FeedbackTokenRoute
  '/mentors/interest': typeof MentorsInterestRoute
  '/my-listing/$token': typeof MyListingTokenRoute
  '/profile/$id': typeof ProfileIdRoute
  '/request-mentorship/$mentorId': typeof RequestMentorshipMentorIdRoute
  '/request/$token': typeof RequestTokenRoute
  '/youth/opportunities': typeof YouthOpportunitiesRoute
  '/youth/post-opportunity': typeof YouthPostOpportunityRoute
  '/youth/register': typeof YouthRegisterRoute
  '/apprenticeships/': typeof ApprenticeshipsIndexRoute
  '/request-mentorship/': typeof RequestMentorshipIndexRoute
  '/youth/': typeof YouthIndexRoute
  '/_authenticated/admin/apprenticeships': typeof AuthenticatedAdminApprenticeshipsRoute
  '/_authenticated/admin/noticeboard': typeof AuthenticatedAdminNoticeboardRoute
  '/_authenticated/admin/youth-opportunities': typeof AuthenticatedAdminYouthOpportunitiesRoute
  '/_authenticated/youth/portfolio': typeof AuthenticatedYouthPortfolioRoute
  '/api/public/contact-request': typeof ApiPublicContactRequestRoute
  '/directory/$type/$id': typeof DirectoryTypeIdRoute
  '/youth/parent-consent/$token': typeof YouthParentConsentTokenRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/apprentices/$id': typeof AuthenticatedAdminApprenticesIdRoute
  '/_authenticated/admin/providers/$id': typeof AuthenticatedAdminProvidersIdRoute
  '/_authenticated/admin/youth/$id': typeof AuthenticatedAdminYouthIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/admin/youth/': typeof AuthenticatedAdminYouthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advertise'
    | '/apprenticeships'
    | '/auth'
    | '/contact'
    | '/directory'
    | '/disclaimer'
    | '/donate'
    | '/find-help'
    | '/how-it-works'
    | '/privacy'
    | '/register-provider'
    | '/request-support'
    | '/reset-password'
    | '/safeguarding-policy'
    | '/terms'
    | '/youth'
    | '/my-advert'
    | '/my-requests'
    | '/profile'
    | '/apprenticeships/become-mentor'
    | '/apprenticeships/impact'
    | '/apprenticeships/mentors'
    | '/apprenticeships/opportunities'
    | '/apprenticeships/register-apprentice'
    | '/apprenticeships/register-provider'
    | '/feedback/$token'
    | '/mentors/interest'
    | '/my-listing/$token'
    | '/profile/$id'
    | '/request-mentorship/$mentorId'
    | '/request/$token'
    | '/youth/opportunities'
    | '/youth/post-opportunity'
    | '/youth/register'
    | '/apprenticeships/'
    | '/request-mentorship/'
    | '/youth/'
    | '/admin/apprenticeships'
    | '/admin/noticeboard'
    | '/admin/youth-opportunities'
    | '/youth/portfolio'
    | '/api/public/contact-request'
    | '/directory/$type/$id'
    | '/youth/parent-consent/$token'
    | '/admin/'
    | '/admin/apprentices/$id'
    | '/admin/providers/$id'
    | '/admin/youth/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/youth/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advertise'
    | '/auth'
    | '/contact'
    | '/directory'
    | '/disclaimer'
    | '/donate'
    | '/find-help'
    | '/how-it-works'
    | '/privacy'
    | '/register-provider'
    | '/request-support'
    | '/reset-password'
    | '/safeguarding-policy'
    | '/terms'
    | '/my-advert'
    | '/my-requests'
    | '/profile'
    | '/apprenticeships/become-mentor'
    | '/apprenticeships/impact'
    | '/apprenticeships/mentors'
    | '/apprenticeships/opportunities'
    | '/apprenticeships/register-apprentice'
    | '/apprenticeships/register-provider'
    | '/feedback/$token'
    | '/mentors/interest'
    | '/my-listing/$token'
    | '/profile/$id'
    | '/request-mentorship/$mentorId'
    | '/request/$token'
    | '/youth/opportunities'
    | '/youth/post-opportunity'
    | '/youth/register'
    | '/apprenticeships'
    | '/request-mentorship'
    | '/youth'
    | '/admin/apprenticeships'
    | '/admin/noticeboard'
    | '/admin/youth-opportunities'
    | '/youth/portfolio'
    | '/api/public/contact-request'
    | '/directory/$type/$id'
    | '/youth/parent-consent/$token'
    | '/admin'
    | '/admin/apprentices/$id'
    | '/admin/providers/$id'
    | '/admin/youth/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/youth'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/advertise'
    | '/apprenticeships'
    | '/auth'
    | '/contact'
    | '/directory'
    | '/disclaimer'
    | '/donate'
    | '/find-help'
    | '/how-it-works'
    | '/privacy'
    | '/register-provider'
    | '/request-support'
    | '/reset-password'
    | '/safeguarding-policy'
    | '/terms'
    | '/youth'
    | '/_authenticated/my-advert'
    | '/_authenticated/my-requests'
    | '/_authenticated/profile'
    | '/apprenticeships/become-mentor'
    | '/apprenticeships/impact'
    | '/apprenticeships/mentors'
    | '/apprenticeships/opportunities'
    | '/apprenticeships/register-apprentice'
    | '/apprenticeships/register-provider'
    | '/feedback/$token'
    | '/mentors/interest'
    | '/my-listing/$token'
    | '/profile/$id'
    | '/request-mentorship/$mentorId'
    | '/request/$token'
    | '/youth/opportunities'
    | '/youth/post-opportunity'
    | '/youth/register'
    | '/apprenticeships/'
    | '/request-mentorship/'
    | '/youth/'
    | '/_authenticated/admin/apprenticeships'
    | '/_authenticated/admin/noticeboard'
    | '/_authenticated/admin/youth-opportunities'
    | '/_authenticated/youth/portfolio'
    | '/api/public/contact-request'
    | '/directory/$type/$id'
    | '/youth/parent-consent/$token'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/apprentices/$id'
    | '/_authenticated/admin/providers/$id'
    | '/_authenticated/admin/youth/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/_authenticated/admin/youth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdvertiseRoute: typeof AdvertiseRoute
  ApprenticeshipsRoute: typeof ApprenticeshipsRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DirectoryRoute: typeof DirectoryRouteWithChildren
  DisclaimerRoute: typeof DisclaimerRoute
  DonateRoute: typeof DonateRoute
  FindHelpRoute: typeof FindHelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterProviderRoute: typeof RegisterProviderRoute
  RequestSupportRoute: typeof RequestSupportRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SafeguardingPolicyRoute: typeof SafeguardingPolicyRoute
  TermsRoute: typeof TermsRoute
  YouthRoute: typeof YouthRouteWithChildren
  FeedbackTokenRoute: typeof FeedbackTokenRoute
  MentorsInterestRoute: typeof MentorsInterestRoute
  MyListingTokenRoute: typeof MyListingTokenRoute
  ProfileIdRoute: typeof ProfileIdRoute
  RequestMentorshipMentorIdRoute: typeof RequestMentorshipMentorIdRoute
  RequestTokenRoute: typeof RequestTokenRoute
  RequestMentorshipIndexRoute: typeof RequestMentorshipIndexRoute
  ApiPublicContactRequestRoute: typeof ApiPublicContactRequestRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youth': {
      id: '/youth'
      path: '/youth'
      fullPath: '/youth'
      preLoaderRoute: typeof YouthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safeguarding-policy': {
      id: '/safeguarding-policy'
      path: '/safeguarding-policy'
      fullPath: '/safeguarding-policy'
      preLoaderRoute: typeof SafeguardingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-support': {
      id: '/request-support'
      path: '/request-support'
      fullPath: '/request-support'
      preLoaderRoute: typeof RequestSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-provider': {
      id: '/register-provider'
      path: '/register-provider'
      fullPath: '/register-provider'
      preLoaderRoute: typeof RegisterProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-help': {
      id: '/find-help'
      path: '/find-help'
      fullPath: '/find-help'
      preLoaderRoute: typeof FindHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apprenticeships': {
      id: '/apprenticeships'
      path: '/apprenticeships'
      fullPath: '/apprenticeships'
      preLoaderRoute: typeof ApprenticeshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youth/': {
      id: '/youth/'
      path: '/'
      fullPath: '/youth/'
      preLoaderRoute: typeof YouthIndexRouteImport
      parentRoute: typeof YouthRoute
    }
    '/request-mentorship/': {
      id: '/request-mentorship/'
      path: '/request-mentorship'
      fullPath: '/request-mentorship/'
      preLoaderRoute: typeof RequestMentorshipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apprenticeships/': {
      id: '/apprenticeships/'
      path: '/'
      fullPath: '/apprenticeships/'
      preLoaderRoute: typeof ApprenticeshipsIndexRouteImport
      parentRoute: typeof ApprenticeshipsRoute
    }
    '/youth/register': {
      id: '/youth/register'
      path: '/register'
      fullPath: '/youth/register'
      preLoaderRoute: typeof YouthRegisterRouteImport
      parentRoute: typeof YouthRoute
    }
    '/youth/post-opportunity': {
      id: '/youth/post-opportunity'
      path: '/post-opportunity'
      fullPath: '/youth/post-opportunity'
      preLoaderRoute: typeof YouthPostOpportunityRouteImport
      parentRoute: typeof YouthRoute
    }
    '/youth/opportunities': {
      id: '/youth/opportunities'
      path: '/opportunities'
      fullPath: '/youth/opportunities'
      preLoaderRoute: typeof YouthOpportunitiesRouteImport
      parentRoute: typeof YouthRoute
    }
    '/request/$token': {
      id: '/request/$token'
      path: '/request/$token'
      fullPath: '/request/$token'
      preLoaderRoute: typeof RequestTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-mentorship/$mentorId': {
      id: '/request-mentorship/$mentorId'
      path: '/request-mentorship/$mentorId'
      fullPath: '/request-mentorship/$mentorId'
      preLoaderRoute: typeof RequestMentorshipMentorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-listing/$token': {
      id: '/my-listing/$token'
      path: '/my-listing/$token'
      fullPath: '/my-listing/$token'
      preLoaderRoute: typeof MyListingTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors/interest': {
      id: '/mentors/interest'
      path: '/mentors/interest'
      fullPath: '/mentors/interest'
      preLoaderRoute: typeof MentorsInterestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$token': {
      id: '/feedback/$token'
      path: '/feedback/$token'
      fullPath: '/feedback/$token'
      preLoaderRoute: typeof FeedbackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apprenticeships/register-provider': {
      id: '/apprenticeships/register-provider'
      path: '/register-provider'
      fullPath: '/apprenticeships/register-provider'
      preLoaderRoute: typeof ApprenticeshipsRegisterProviderRouteImport
      parentRoute: typeof ApprenticeshipsRoute
    }
    '/apprenticeships/register-apprentice': {
      id: '/apprenticeships/register-apprentice'
      path: '/register-apprentice'
      fullPath: '/apprenticeships/register-apprentice'
      preLoaderRoute: typeof ApprenticeshipsRegisterApprenticeRouteImport
      parentRoute: typeof ApprenticeshipsRoute
    }
    '/apprenticeships/opportunities': {
      id: '/apprenticeships/opportunities'
      path: '/opportunities'
      fullPath: '/apprenticeships/opportunities'
      preLoaderRoute: typeof ApprenticeshipsOpportunitiesRouteImport
      parentRoute: typeof ApprenticeshipsRoute
    }
    '/apprenticeships/mentors': {
      id: '/apprenticeships/mentors'
      path: '/mentors'
      fullPath: '/apprenticeships/mentors'
      preLoaderRoute: typeof ApprenticeshipsMentorsRouteImport
      parentRoute: typeof ApprenticeshipsRoute
    }
    '/apprenticeships/impact': {
      id: '/apprenticeships/impact'
      path: '/impact'
      fullPath: '/apprenticeships/impact'
      preLoaderRoute: typeof ApprenticeshipsImpactRouteImport
      parentRoute: typeof ApprenticeshipsRoute
    }
    '/apprenticeships/become-mentor': {
      id: '/apprenticeships/become-mentor'
      path: '/become-mentor'
      fullPath: '/apprenticeships/become-mentor'
      preLoaderRoute: typeof ApprenticeshipsBecomeMentorRouteImport
      parentRoute: typeof ApprenticeshipsRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-requests': {
      id: '/_authenticated/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof AuthenticatedMyRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-advert': {
      id: '/_authenticated/my-advert'
      path: '/my-advert'
      fullPath: '/my-advert'
      preLoaderRoute: typeof AuthenticatedMyAdvertRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/youth/parent-consent/$token': {
      id: '/youth/parent-consent/$token'
      path: '/parent-consent/$token'
      fullPath: '/youth/parent-consent/$token'
      preLoaderRoute: typeof YouthParentConsentTokenRouteImport
      parentRoute: typeof YouthRoute
    }
    '/directory/$type/$id': {
      id: '/directory/$type/$id'
      path: '/$type/$id'
      fullPath: '/directory/$type/$id'
      preLoaderRoute: typeof DirectoryTypeIdRouteImport
      parentRoute: typeof DirectoryRoute
    }
    '/api/public/contact-request': {
      id: '/api/public/contact-request'
      path: '/api/public/contact-request'
      fullPath: '/api/public/contact-request'
      preLoaderRoute: typeof ApiPublicContactRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/youth/portfolio': {
      id: '/_authenticated/youth/portfolio'
      path: '/youth/portfolio'
      fullPath: '/youth/portfolio'
      preLoaderRoute: typeof AuthenticatedYouthPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/youth-opportunities': {
      id: '/_authenticated/admin/youth-opportunities'
      path: '/admin/youth-opportunities'
      fullPath: '/admin/youth-opportunities'
      preLoaderRoute: typeof AuthenticatedAdminYouthOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/noticeboard': {
      id: '/_authenticated/admin/noticeboard'
      path: '/admin/noticeboard'
      fullPath: '/admin/noticeboard'
      preLoaderRoute: typeof AuthenticatedAdminNoticeboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/apprenticeships': {
      id: '/_authenticated/admin/apprenticeships'
      path: '/admin/apprenticeships'
      fullPath: '/admin/apprenticeships'
      preLoaderRoute: typeof AuthenticatedAdminApprenticeshipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/youth/': {
      id: '/_authenticated/admin/youth/'
      path: '/admin/youth'
      fullPath: '/admin/youth/'
      preLoaderRoute: typeof AuthenticatedAdminYouthIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/youth/$id': {
      id: '/_authenticated/admin/youth/$id'
      path: '/admin/youth/$id'
      fullPath: '/admin/youth/$id'
      preLoaderRoute: typeof AuthenticatedAdminYouthIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/providers/$id': {
      id: '/_authenticated/admin/providers/$id'
      path: '/admin/providers/$id'
      fullPath: '/admin/providers/$id'
      preLoaderRoute: typeof AuthenticatedAdminProvidersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/apprentices/$id': {
      id: '/_authenticated/admin/apprentices/$id'
      path: '/admin/apprentices/$id'
      fullPath: '/admin/apprentices/$id'
      preLoaderRoute: typeof AuthenticatedAdminApprenticesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMyAdvertRoute: typeof AuthenticatedMyAdvertRoute
  AuthenticatedMyRequestsRoute: typeof AuthenticatedMyRequestsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminApprenticeshipsRoute: typeof AuthenticatedAdminApprenticeshipsRoute
  AuthenticatedAdminNoticeboardRoute: typeof AuthenticatedAdminNoticeboardRoute
  AuthenticatedAdminYouthOpportunitiesRoute: typeof AuthenticatedAdminYouthOpportunitiesRoute
  AuthenticatedYouthPortfolioRoute: typeof AuthenticatedYouthPortfolioRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminApprenticesIdRoute: typeof AuthenticatedAdminApprenticesIdRoute
  AuthenticatedAdminProvidersIdRoute: typeof AuthenticatedAdminProvidersIdRoute
  AuthenticatedAdminYouthIdRoute: typeof AuthenticatedAdminYouthIdRoute
  AuthenticatedAdminYouthIndexRoute: typeof AuthenticatedAdminYouthIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMyAdvertRoute: AuthenticatedMyAdvertRoute,
  AuthenticatedMyRequestsRoute: AuthenticatedMyRequestsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminApprenticeshipsRoute:
    AuthenticatedAdminApprenticeshipsRoute,
  AuthenticatedAdminNoticeboardRoute: AuthenticatedAdminNoticeboardRoute,
  AuthenticatedAdminYouthOpportunitiesRoute:
    AuthenticatedAdminYouthOpportunitiesRoute,
  AuthenticatedYouthPortfolioRoute: AuthenticatedYouthPortfolioRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminApprenticesIdRoute: AuthenticatedAdminApprenticesIdRoute,
  AuthenticatedAdminProvidersIdRoute: AuthenticatedAdminProvidersIdRoute,
  AuthenticatedAdminYouthIdRoute: AuthenticatedAdminYouthIdRoute,
  AuthenticatedAdminYouthIndexRoute: AuthenticatedAdminYouthIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApprenticeshipsRouteChildren {
  ApprenticeshipsBecomeMentorRoute: typeof ApprenticeshipsBecomeMentorRoute
  ApprenticeshipsImpactRoute: typeof ApprenticeshipsImpactRoute
  ApprenticeshipsMentorsRoute: typeof ApprenticeshipsMentorsRoute
  ApprenticeshipsOpportunitiesRoute: typeof ApprenticeshipsOpportunitiesRoute
  ApprenticeshipsRegisterApprenticeRoute: typeof ApprenticeshipsRegisterApprenticeRoute
  ApprenticeshipsRegisterProviderRoute: typeof ApprenticeshipsRegisterProviderRoute
  ApprenticeshipsIndexRoute: typeof ApprenticeshipsIndexRoute
}

const ApprenticeshipsRouteChildren: ApprenticeshipsRouteChildren = {
  ApprenticeshipsBecomeMentorRoute: ApprenticeshipsBecomeMentorRoute,
  ApprenticeshipsImpactRoute: ApprenticeshipsImpactRoute,
  ApprenticeshipsMentorsRoute: ApprenticeshipsMentorsRoute,
  ApprenticeshipsOpportunitiesRoute: ApprenticeshipsOpportunitiesRoute,
  ApprenticeshipsRegisterApprenticeRoute:
    ApprenticeshipsRegisterApprenticeRoute,
  ApprenticeshipsRegisterProviderRoute: ApprenticeshipsRegisterProviderRoute,
  ApprenticeshipsIndexRoute: ApprenticeshipsIndexRoute,
}

const ApprenticeshipsRouteWithChildren = ApprenticeshipsRoute._addFileChildren(
  ApprenticeshipsRouteChildren,
)

interface DirectoryRouteChildren {
  DirectoryTypeIdRoute: typeof DirectoryTypeIdRoute
}

const DirectoryRouteChildren: DirectoryRouteChildren = {
  DirectoryTypeIdRoute: DirectoryTypeIdRoute,
}

const DirectoryRouteWithChildren = DirectoryRoute._addFileChildren(
  DirectoryRouteChildren,
)

interface YouthRouteChildren {
  YouthOpportunitiesRoute: typeof YouthOpportunitiesRoute
  YouthPostOpportunityRoute: typeof YouthPostOpportunityRoute
  YouthRegisterRoute: typeof YouthRegisterRoute
  YouthIndexRoute: typeof YouthIndexRoute
  YouthParentConsentTokenRoute: typeof YouthParentConsentTokenRoute
}

const YouthRouteChildren: YouthRouteChildren = {
  YouthOpportunitiesRoute: YouthOpportunitiesRoute,
  YouthPostOpportunityRoute: YouthPostOpportunityRoute,
  YouthRegisterRoute: YouthRegisterRoute,
  YouthIndexRoute: YouthIndexRoute,
  YouthParentConsentTokenRoute: YouthParentConsentTokenRoute,
}

const YouthRouteWithChildren = YouthRoute._addFileChildren(YouthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdvertiseRoute: AdvertiseRoute,
  ApprenticeshipsRoute: ApprenticeshipsRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DirectoryRoute: DirectoryRouteWithChildren,
  DisclaimerRoute: DisclaimerRoute,
  DonateRoute: DonateRoute,
  FindHelpRoute: FindHelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterProviderRoute: RegisterProviderRoute,
  RequestSupportRoute: RequestSupportRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SafeguardingPolicyRoute: SafeguardingPolicyRoute,
  TermsRoute: TermsRoute,
  YouthRoute: YouthRouteWithChildren,
  FeedbackTokenRoute: FeedbackTokenRoute,
  MentorsInterestRoute: MentorsInterestRoute,
  MyListingTokenRoute: MyListingTokenRoute,
  ProfileIdRoute: ProfileIdRoute,
  RequestMentorshipMentorIdRoute: RequestMentorshipMentorIdRoute,
  RequestTokenRoute: RequestTokenRoute,
  RequestMentorshipIndexRoute: RequestMentorshipIndexRoute,
  ApiPublicContactRequestRoute: ApiPublicContactRequestRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
